name: clean_note
description: note_app_with_clean_architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  sqflite: ^2.1.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  freezed: ^2.2.1
  build_runner: ^2.3.2

  # 테스트용 sqflite
  sqflite_common_ffi: ^2.2.0+1

flutter:

  uses-material-design: true
